
#static is here mvpland_static
#postgresql -- mvpland
#username -- cfedeploy
#password -- ##


"""
Django settings for ecommerce2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf import settings

if not settings.DEBUG:
	import os
        PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	#root of project

	# Quick-start development settings - unsuitable for production
	# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

	# SECURITY WARNING: keep the secret key used in production secret!


	# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = True
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ADMINS = (
		("vinay", "vinaykumar.vk2007@gmail.com"),

		)

ALLOWED_HOSTS = ['*']
	#purchasing domain name http://name.com

	
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'vinaykumar.vk2007@gmail.com'
EMAIL_HOST_PASSWORD = '8090289260'
EMAIL_PORT = 587

	''' 
	If using gmail, you will need to
	unlock Captcha to enable Django 
	to  send for you:
	https://accounts.google.com/displayunlockcaptcha
	'''


	# Application definition


